# Generated by Django 5.1.4 on 2026-09-09 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_pagecontent_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='canonical',
            field=models.URLField(blank=True, help_text='Обычно оставьте пустым: адрес определяется автоматически.', verbose_name='Основной адрес страницы (canonical)'),
        ),
        migrations.AddField(
            model_name='category',
            name='h1',
            field=models.CharField(blank=True, max_length=220, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Описание в поиске'),
        ),
        migrations.AddField(
            model_name='category',
            name='og_description',
            field=models.TextField(blank=True, verbose_name='Описание при отправке ссылки'),
        ),
        migrations.AddField(
            model_name='category',
            name='og_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_og_uses', to='store.sitemedia', verbose_name='Изображение при отправке ссылки'),
        ),
        migrations.AddField(
            model_name='category',
            name='og_title',
            field=models.CharField(blank=True, max_length=220, verbose_name='Заголовок при отправке ссылки'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title',
            field=models.CharField(blank=True, max_length=220, verbose_name='Заголовок в поиске'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='canonical',
            field=models.URLField(blank=True, help_text='Оставьте пустым для автоматического адреса.', verbose_name='Основной адрес страницы (canonical)'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='hero_button_url',
            field=models.CharField(blank=True, max_length=220, verbose_name='Ссылка главной кнопки'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='hero_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hero_uses', to='store.sitemedia', verbose_name='Главное изображение из медиатеки'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='mobile_hero_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mobile_hero_uses', to='store.sitemedia', verbose_name='Мобильное изображение из медиатеки'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='noindex',
            field=models.BooleanField(default=False, verbose_name='Не показывать страницу в поиске'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='og_description',
            field=models.TextField(blank=True, verbose_name='Описание при отправке ссылки'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='og_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='page_og_uses', to='store.sitemedia', verbose_name='Изображение при отправке ссылки'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='og_title',
            field=models.CharField(blank=True, max_length=220, verbose_name='Заголовок при отправке ссылки'),
        ),
        migrations.AddField(
            model_name='product',
            name='canonical',
            field=models.URLField(blank=True, help_text='Обычно оставьте пустым: адрес определяется автоматически.', verbose_name='Основной адрес страницы (canonical)'),
        ),
        migrations.AddField(
            model_name='product',
            name='h1',
            field=models.CharField(blank=True, max_length=220, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Описание в поиске'),
        ),
        migrations.AddField(
            model_name='product',
            name='og_description',
            field=models.TextField(blank=True, verbose_name='Описание при отправке ссылки'),
        ),
        migrations.AddField(
            model_name='product',
            name='og_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_og_uses', to='store.sitemedia', verbose_name='Изображение при отправке ссылки'),
        ),
        migrations.AddField(
            model_name='product',
            name='og_title',
            field=models.CharField(blank=True, max_length=220, verbose_name='Заголовок при отправке ссылки'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, max_length=220, verbose_name='Заголовок в поиске'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='allow_indexing',
            field=models.BooleanField(default=True, verbose_name='Разрешить индексацию сайта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_label',
            field=models.CharField(default='Консультация', max_length=28, verbose_name='Основная кнопка: текст'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_url',
            field=models.CharField(default='/contacts/#request-form', max_length=220, verbose_name='Основная кнопка: ссылка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='favicon_uses', to='store.sitemedia', verbose_name='Иконка вкладки из медиатеки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_extra_text',
            field=models.TextField(blank=True, verbose_name='Дополнительный текст подвала'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_legal_text',
            field=models.TextField(blank=True, verbose_name='Юридическая информация в подвале'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logo_uses', to='store.sitemedia', verbose_name='Логотип из медиатеки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_og_uses', to='store.sitemedia', verbose_name='Изображение для отправки ссылок по умолчанию'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='public_url',
            field=models.URLField(blank=True, help_text='Например, https://example.ru. Используется для canonical и карты сайта.', verbose_name='Основной адрес сайта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='Описание компании для поисковых систем'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_header_account',
            field=models.BooleanField(default=True, verbose_name='Показывать профиль в шапке'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_header_contacts',
            field=models.BooleanField(default=True, verbose_name='Показывать контакты в шапке'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_header_cta',
            field=models.BooleanField(default=False, verbose_name='Показывать основную кнопку в шапке'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_header_favorites',
            field=models.BooleanField(default=True, verbose_name='Показывать избранное в шапке'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='page',
            field=models.CharField(choices=[('home', 'Главная'), ('catalog', 'Каталог'), ('team', 'Команда'), ('contacts', 'Контакты'), ('privacy', 'Политика конфиденциальности'), ('offer', 'Оферта')], max_length=40, unique=True, verbose_name='Страница'),
        ),
        migrations.CreateModel(
            name='SiteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('header', 'Шапка'), ('footer', 'Подвал'), ('social', 'Социальные сети')], default='header', max_length=20, verbose_name='Где показывать')),
                ('label', models.CharField(max_length=80, verbose_name='Название ссылки')),
                ('url', models.CharField(max_length=500, verbose_name='Адрес ссылки')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='store.sitesettings')),
            ],
            options={
                'verbose_name': 'Ссылка сайта',
                'verbose_name_plural': 'Ссылки сайта',
                'ordering': ['location', 'sort_order', 'pk'],
            },
        ),
    ]
