from django.urls import path

from . import cms_views, views


urlpatterns = [
    path("", views.home, name="home"),
    path("catalog/", views.catalog, name="catalog"),
    path("account/login/", views.account_login, name="account_login"),
    path("account/register/", views.account_register, name="account_register"),
    path("account/verify/", views.account_verify, name="account_verify"),
    path("account/password-reset/", views.account_password_reset_request, name="account_password_reset"),
    path("account/password-reset/confirm/", views.account_password_reset_confirm, name="account_password_reset_confirm"),
    path("account/logout/", views.account_logout, name="account_logout"),
    path("requests/create/", views.create_customer_request, name="create_customer_request"),
    path("documents/<slug:slug>/", views.document_page, name="document_page"),
    path("api/categories/", views.api_categories, name="api_categories"),
    path("api/products/", views.api_products, name="api_products"),
    path("api/cart/", views.api_cart, name="api_cart"),
    path("api/management/orders/", views.api_management_orders, name="api_management_orders"),
    path("api/management/orders/<int:order_id>/", views.api_management_order_detail, name="api_management_order_detail"),
    path("cart/add/", views.add_to_cart, name="add_to_cart"),
    path("cart/update/", views.update_cart, name="update_cart"),
    path("cart/clear/", views.clear_cart, name="clear_cart"),
    path("cart/checkout/", views.checkout_order, name="checkout_order"),
    path("favorites/toggle/", views.toggle_favorite, name="toggle_favorite"),
    path("management/login/", cms_views.ManagementLoginView.as_view(), name="management_login"),
    path("management/logout/", cms_views.management_logout, name="management_logout"),
    path("management/", cms_views.dashboard, name="management_dashboard"),
    path("management/products/", cms_views.product_list, name="management_products"),
    path("management/products/new/", cms_views.product_form, name="management_product_new"),
    path("management/products/<int:product_id>/edit/", cms_views.product_form, name="management_product_edit"),
    path("management/products/<int:product_id>/duplicate/", cms_views.product_duplicate, name="management_product_duplicate"),
    path("management/products/<int:product_id>/delete/", cms_views.product_delete, name="management_product_delete"),
    path("management/products/bulk/", cms_views.product_bulk_action, name="management_product_bulk"),
    path("management/orders/", cms_views.order_list, name="management_orders"),
    path("management/orders/<int:order_id>/", cms_views.order_detail, name="management_order_detail"),
    path("management/categories/", cms_views.category_list, name="management_categories"),
    path("management/categories/new/", cms_views.category_form, name="management_category_new"),
    path("management/categories/<int:category_id>/edit/", cms_views.category_form, name="management_category_edit"),
    path("management/categories/<int:category_id>/duplicate/", cms_views.category_duplicate, name="management_category_duplicate"),
    path("management/categories/<int:category_id>/delete/", cms_views.category_delete, name="management_category_delete"),
    path("management/categories/bulk/", cms_views.category_bulk_action, name="management_category_bulk"),
    path("management/employees/", cms_views.employee_list, name="management_employees"),
    path("management/employees/new/", cms_views.employee_form, name="management_employee_new"),
    path("management/employees/<int:employee_id>/edit/", cms_views.employee_form, name="management_employee_edit"),
    path("management/employees/<int:employee_id>/duplicate/", cms_views.employee_duplicate, name="management_employee_duplicate"),
    path("management/employees/<int:employee_id>/delete/", cms_views.employee_delete, name="management_employee_delete"),
    path("management/employees/bulk/", cms_views.employee_bulk_action, name="management_employee_bulk"),
    path("management/fields/", cms_views.field_list, name="management_fields"),
    path("management/fields/new/", cms_views.field_form, name="management_field_new"),
    path("management/fields/<int:field_id>/edit/", cms_views.field_form, name="management_field_edit"),
    path("management/fields/<int:field_id>/delete/", cms_views.field_delete, name="management_field_delete"),
    path("management/settings/", cms_views.site_settings, name="management_settings"),
    path("management/requests/", cms_views.request_list, name="management_requests"),
    path("management/requests/bulk/", cms_views.request_bulk_action, name="management_request_bulk"),
    path("management/pages/", cms_views.page_content_list, name="management_pages"),
    path("management/pages/new/", cms_views.page_content_form, name="management_page_new"),
    path("management/pages/<int:page_id>/edit/", cms_views.page_content_form, name="management_page_edit"),
    path("management/pages/<int:page_id>/delete/", cms_views.page_content_delete, name="management_page_delete"),
    path("team/", views.team, name="team"),
    path("contacts/", views.contacts, name="contacts"),
]
